server:
  port: 8080 #端口
  servlet:
    context-path: /
  tomcat:
    min-spare-threads: 20
    max-threads: 2000
    connection-timeout: 10000
spring:
  application:
    name:  @project.name@
    #文件上传配置
  #数据库 配置
  datasource:
    # 基本属性
    name: @db.jdbc.name@
    url: @db.jdbc.url@
    username: @db.jdbc.username@
    password: '@db.jdbc.password@'
    # 可以不配置，根据url自动识别，建议配置
    # driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      min-idle: @db.jdbc.minimum-idle@
      max-active: @db.jdbc.maximum-pool-size@
      # 数据库连接超时时间,默认30秒，即30000
      max-wait: @db.jdbc.idle-timeout@
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB

#日志输出
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl