spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
      username: root
      password: Cqs@1996
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jeesite?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      initialSize: 5
      minIdle: 5
      maxActive: 20


